# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  database: asset_development
  username: root
  password: monkey 

production:
  adapter: mysql
  database: asset_production
  username: root
  password: monkey 

test: &test
  adapter: mysql
  database: asset_test
  username: root
  password: monkey   
cucumber:
  <<: *test